language: node_js
node_js:
- 10

dist: trusty
sudo: false
cache: yarn

script:
- yarn hello
- yarn bye

branches:
  only:
  - beta

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true