language: node_js
node_js:
  - 10

dist: trusty
sudo: false
cache: yarn

stages:
  - name: node hoge
    if: type = pull_request AND branch IN hoge
  - name: node fuga
    if: type = pull_request AND branch =~ /fuga\/.*/

jobs:
  include:
    - stage: node hoge
      script: node hoge-index.js
    - stage: node fuga
      script: node fuga-index.js