language: node_js
node_js:
  - 10

dist: trusty
sudo: false
cache: yarn

stages:
  - name: test
    if: type = pull_request
  - name: npm deploy
    if: tag =~ /^v?[0-9\\.]+/

jobs:
  include:
    - stage: test
      script: yarn test
    - stage: npm deploy
      deploy:
        provider: npm
        email: $NPM_EMAIL_DEMO
        api_key: $NPM_TOKEN_DEMO
        skip_cleanup: true
