language: node_js
node_js:
  - 10

dist: trusty
sudo: false
cache: yarn

stages:
  - name: node
    if: pull_request

jobs:
  include:
    - stage: node

      if: branch =~ /^hoge\/.*$/
      script: node hoge-index.js

      if: branch =~ /^fuga\/.*$/
      script: node fuga-index.js